name: mosaic_traj
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - geos=3.10.2
  - jbig=2.1
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libwebp-base=1.2.2
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - ncurses=6.3
  - openssl=3.0.2
  - pip=22.0.4
  - proj=9.0.0
  - python=3.7.12
  - python_abi=3.7
  - readline=8.1
  - setuptools=62.1.0
  - sqlite=3.38.2
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - cartopy==0.20.2
    - certifi==2021.10.8
    - cycler==0.11.0
    - fonttools==4.33.2
    - kiwisolver==1.4.2
    - matplotlib==3.5.1
    - numpy==1.21.6
    - packaging==21.3
    - pandas==1.3.5
    - pillow==9.1.0
    - pyparsing==3.0.8
    - pyproj==3.2.1
    - pyshp==2.2.0
    - python-dateutil==2.8.2
    - pytz==2022.1
    - shapely==1.8.1.post1
    - six==1.16.0
    - typing-extensions==4.2.0
